php7:
  build: .
  dockerfile: etc/docker/process_dockerfile
  volumes:
    - ./repo:/var/www/html/
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
  ports:
    - "80:80"
    - "8080:8080"
  links:
    - mysql

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=db_test
  volumes: 
    - ./etc/mysql:/docker-entrypoint-initdb.d
    - ./etc/my.cnf:/etc/mysql/my.cnf

    
